//
// Automatically generated by AjGenesis
// Node.js Project https://github.com/ajlopez/AjGenesisNode
// Original Project http://www.ajlopez.com/ajgenesis
//

namespace Hello
{
using System;
using System.Collections.Generic;
using System.Text;

    public class Program
    {
        public static void Main(string[] args)
        {
			Console.WriteLine("Hello ${name}");
        }
    }
}

