
// Autogenerated with AjGenesis for Node.js
// https://github.com/ajlopez/AjGenesisNode

public class Hello {
	public static void main(String[] args) {
		System.out.println("Hello ${name}");
	}
}
