'
' Automatically generated by AjGenesis for Node.js
' https://github.com/ajlopez/AjGenesisNode
'

Module Module1

    Sub Main()
        System.Console.WriteLine("Hello ${name}")
    End Sub

End Module
